{"uuid": "0b0dbc4e-241b-43d2-9a6c-c4b0da9a95c9", "children": ["c8125b0c-9194-427b-8f7f-1b1147b8c629"], "befores": [{"name": "driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_NAME_NOT_RESOLVED\n  (Session info: chrome=126.0.6478.182)\nStacktrace:\n\tGetHandleVerifier [0x00007FF7AA971F52+60322]\n\t(No symbol) [0x00007FF7AA8ECEC9]\n\t(No symbol) [0x00007FF7AA7A7EBA]\n\t(No symbol) [0x00007FF7AA79FEA2]\n\t(No symbol) [0x00007FF7AA7909C4]\n\t(No symbol) [0x00007FF7AA792212]\n\t(No symbol) [0x00007FF7AA790CF1]\n\t(No symbol) [0x00007FF7AA7904D1]\n\t(No symbol) [0x00007FF7AA790410]\n\t(No symbol) [0x00007FF7AA78E39D]\n\t(No symbol) [0x00007FF7AA78E9DC]\n\t(No symbol) [0x00007FF7AA7AAC91]\n\t(No symbol) [0x00007FF7AA83C5FE]\n\t(No symbol) [0x00007FF7AA81C21A]\n\t(No symbol) [0x00007FF7AA83BC80]\n\t(No symbol) [0x00007FF7AA81BFC3]\n\t(No symbol) [0x00007FF7AA7E9617]\n\t(No symbol) [0x00007FF7AA7EA211]\n\tGetHandleVerifier [0x00007FF7AAC894AD+3301629]\n\tGetHandleVerifier [0x00007FF7AACD36D3+3605283]\n\tGetHandleVerifier [0x00007FF7AACC9450+3563680]\n\tGetHandleVerifier [0x00007FF7AAA24326+790390]\n\t(No symbol) [0x00007FF7AA8F750F]\n\t(No symbol) [0x00007FF7AA8F3404]\n\t(No symbol) [0x00007FF7AA8F3592]\n\t(No symbol) [0x00007FF7AA8E2F9F]\n\tBaseThreadInitThunk [0x00007FFFB226257D+29]\n\tRtlUserThreadStart [0x00007FFFB3B8AF28+40]\n\n", "trace": "  File \"C:\\Users\\Laffy\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"C:\\Users\\Laffy\\PycharmProjects\\Diplom_3\\.venv\\Lib\\site-packages\\_pytest\\setuponly.py\", line 36, in pytest_fixture_setup\n    return (yield)\n            ^^^^^\n  File \"C:\\Users\\Laffy\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\pluggy\\_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Laffy\\PycharmProjects\\Diplom_3\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1125, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Laffy\\PycharmProjects\\Diplom_3\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 880, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Laffy\\PycharmProjects\\Diplom_3\\tests\\conftest.py\", line 24, in driver\n    driver.get(data.BASE_URL)\n  File \"C:\\Users\\Laffy\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 356, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\Laffy\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 347, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Laffy\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 229, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1721927206557, "stop": 1721927244518}], "start": 1721927206557, "stop": 1721927244798}